-- AlterTable
ALTER TABLE "AppSettings" ADD COLUMN     "maxTaskHours" DOUBLE PRECISION NOT NULL DEFAULT 4;
ALTER TABLE "AppSettings" ADD COLUMN     "workdayHours" DOUBLE PRECISION NOT NULL DEFAULT 8;
